# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '24' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 24
	pod 'TKSwarmAlert'
    pod 'SwiftyWalkthrough'

  target '24Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '24UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
